import type { Metadata } from "next"; 
import { JetBrains_Mono } from "next/font/google"; 
import "./globals.css"; 
import Header from "@/components/Header"; 
import PageTransition from "@/components/PageTransition"; 
import StairEffect from "@/components/StairEffect"; 
import ParticlesBackground from "@/components/ParticlesBackground"; 
 
const jetBrains = JetBrains_Mono({  
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800",], 
  variable: "--font-jetbrainsMono", 
}); 

export const metadata: Metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
  icons: { 
    icon: "/favicon.ico", 
  }, 
}; 
 
export default function RootLayout({ 
  children, 
}: Readonly<{ 
  children: React.ReactNode; 
}>) { 
  return ( 
    <html lang="en"> 
      <body className={`${jetBrains.variable} 
        min-h-screen 
        bg-gradient-to-br 
        from-gray-200 
        via-gray-300 
        to-gray-400 
        bg-fixed 
        relative
        before:absolute 
        before:inset-0 
        before:bg-[radial-gradient(#9CA3AF_1px,_transparent_1px)] 
        before:bg-[size:16px_16px] 
        before:opacity-30 
        before:pointer-events-none`}>
        <ParticlesBackground>
          <Header />
          <StairEffect />
          <PageTransition>{children}</PageTransition>
        </ParticlesBackground>
      </body>
    </html>
  ); 
} 