import type { Metadata } from "next"; 
import { JetBrains_Mono } from "next/font/google"; 
import "./globals.css";  
import Header from "@/sections/Header";  
import PageTransition from "@/components/PageTransition";  
import StairEffect from "@/components/StairEffect";  
import ParticlesBackground from "@/components/ParticlesBackground"; 
import dynamic from 'next/dynamic'

const AnimatedCursor = dynamic(() => import('react-animated-cursor'), {
  ssr: false
});

const jetBrains = JetBrains_Mono({  
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});  

export const metadata: Metadata = {  
  title: "Create Next App",  
  description: "Generated by create next app",  
  icons: {    
    icon: "/favicon.ico",  
  },  
};  

export default function RootLayout({  
  children,  
}: Readonly<{  
  children: React.ReactNode;  
}>) {  
  return (  
    <html lang="en">
      <body className={`${jetBrains.variable}
        min-h-screen
        bg-gradient-to-br
        from-gray-200
        via-gray-300
        to-gray-400
        bg-fixed
        relative
        before:absolute
        before:inset-0
        before:bg-[radial-gradient(#9CA3AF_1px,_transparent_1px)]
        before:bg-[size:16px_16px]
        before:opacity-30
        before:pointer-events-none`}>
        {/* Cursor with pointer-events-none to allow clicking through */}
        <div className="hidden md:block fixed z-50 pointer-events-none">
          <AnimatedCursor
            color="0, 0, 0"
            innerSize={8}
            outerSize={35}
            innerScale={1}
            outerScale={1.7}
            outerAlpha={0}
            trailingSpeed={4}
            outerStyle={{
              backgroundColor: 'transparent',
              border: '2px solid black'
            }}
          />
        </div>
        <ParticlesBackground>
          <StairEffect />
          <Header />
          <PageTransition>{children}</PageTransition>
        </ParticlesBackground>
      </body>
    </html>
  );  
}